= Productive Enterprise Web Development with ExtJs and Clear Data Builder =
by Viktor Gamov 

== ExtJS MVC application template ==

In this article I'm going to tell you how can use open-source Eclipse Plug-in called Clear Data Builder to be more productive and do more with less while you are developing Enterprise Web applications with ExtJS and Java on the back end.
Here is a small agenda of our todays episode. First,  I want to tell You what is a Clear Data Builder and how and where You can get it and how You can run it. Next I will show you how You can create an ExtJS application for Java project. This ExtJS MVS application will contain all directory structure 
recommended by  MVC Architecture from Sencha's Website and I'll show You how You can run Your application on Tomcat. So, for this you will need Eclipse and You can get latest ??? version of Clear Tool Kit from Eclipse update site. This is the link. Link will be available as a part of show-notes. So, we see that right now major version is 1.1.4. You can always check what is the current available version from this link. Ok. So, once You install it. Let me show that I have it installed in my Eclipse. Here I have Clear Data Builder. And if You see this name over here inside Installed Software in your Eclipse you may sure that you can actually start doing application development. 
So, let me start with the creation of the new project. I'll say New and Other and select here Clear and click Next. And Clear Data Builder supports. First of all Clear Data Builder  is the set of project templates for Enterprise Web Development and on the Java side there is a bunch of different frameworks to support persistence or to support for example dependency injection in this case as Spring. And There is a bunch  of popular framework. You can use these templates to start the project, but in this case  I would like to start a new project  ?? and will show you what is default structure. First of all let me call it episode_1_intro. So, there are different ways how you can link ExtJS framework to this application. In my case I already have installed ExtJS libraries as a part of ??? I actually installed it on the my Web Server on the Tomcat. So I can use this local URL, but also you can just specify any folder in Your machine and Clear Data Builder automatically copy file inside Your project and also You can use the CDN from the Sencha. If you don't want to store these libraries inside your project you can use CDN from Sencha. In this screencast I don't want to use any frameworks, I don't want to use MyBatis or Hibernate, nothing and I don't want to have Spring integration. Ok, so let me click Finish. And as You might see here, first of all you will see output of initial setup of Clear Data Builder. Basically here  Clear Data Builder runs first time and it initializes directory structure and it this case let me show You ???? in the WebContent we have directory structure which is the recommended structure for MVC applications by Sencha. We have directory for application also we have here the HTML wrapper for this application and we will see link to entry of our application. Also by default Clear Data Builder generates empty project with one sample controller and one automatically created viewport. So, in this case let me run this application. And I'll use the Tomcat ?? and remove and add this project??? into Tomcat. And let me add here intro demo and let me start Tomcat. Ok, our application is up and running. Let me switch to web browser to open this application on local host  8080  and name of my project episode_1_intro. Boom! Just in couple minutes we got new project with the ExtJS framework and one fancy button. So, it this case we can see that our application is up and running. Thank You for your time. Please check new episodes on////////